/***************************/
*//* Name: Brooke Alfred
/* Class: CS 3410 */
/* Term: Spring 2025 */
/* Lab #: 3 Part 2 */


SELECT DISTINCT pname
FROM PRODUCTS JOIN ORDERS
ON PRODUCTS.pid = ORDERS.pid;

SELECT DISTINCT cname
FROM CUSTOMERS JOIN ORDERS
ON CUSTOMERS.cid = ORDERS.cid
JOIN PRODUCTS
ON PRODUCTS.pid=ORDERS.pid
WHERE PRODUCTS.pid='p07';

SELECT DISTINCT aname
FROM AGENTS JOIN ORDERS
ON AGENTS.aid = ORDERS.aid
JOIN CUSTOMERS
ON CUSTOMERS.cid=ORDERS.cid
WHERE CUSTOMERS.cid='c003' OR CUSTOMERS.cid='c006';

SELECT DISTINCT cname
FROM CUSTOMERS 
JOIN ORDERS
ON CUSTOMERS.cid = ORDERS.cid
JOIN AGENTS 
ON AGENTS.aid=ORDERS.aid
JOIN PRODUCTS
ON PRODUCTS.pid=ORDERS.pid
WHERE AGENTS.aid='a01' AND PRODUCTS.pid='p01';

SELECT DISTINCT cname, pid
FROM CUSTOMERS
JOIN ORDERS ON CUSTOMERS.cid = ORDERS.cid
JOIN PRODUCTS ON PRODUCTS.pid = ORDERS.pid;

SELECT DISTINCT cname, pname
FROM CUSTOMERS
JOIN ORDERS ON CUSTOMERS.cid = ORDERS.cid
JOIN PRODUCTS ON PRODUCTS.pid = ORDERS.pid;


SELECT DISTINCT cname, SUM(dollars) 
FROM CUSTOMERS
JOIN ORDERS 
ON CUSTOMERS.cid = ORDERS.cid
GROUP BY cname;

SELECT DISTINCT cname, pname, aname
FROM CUSTOMERS
JOIN ORDERS 
ON CUSTOMERS.cid = ORDERS.cid
JOIN PRODUCTS
ON PRODUCTS.pid = ORDERS.pid
JOIN AGENTS
ON AGENTS.aid = ORDERS.aid; 

/* it would show all the combinations of customers and products/



